version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: 'username'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'mydatabase'
    ports:
      - "5432:5432"
    networks:
      - db_network

networks:
  db_network:
    driver: bridge
